### ISSUE TITLE
[Doc] Wrong package name

### ISSUE THREAD

**Issue by Nawick** [florent37/Freezer#1]
Hello Florent,

Just to inform you that's theres is a mistake in your Readme.MD regarding package name.

The following will work (note the fr.xebia instead the com.xebia)

dependencies {
    apt 'fr.xebia.android.freezer:freezer-compiler:1.0.0'
    provided 'fr.xebia.android.freezer:freezer-annotations:1.0.0'
}

Have a good day !

**Comment by florent37** [comment]
thanks :+1:
