### ISSUE TITLE
Cannot find Freezer and error: cannot assign a value to final variable CREATOR

### ISSUE THREAD

**Issue by croccio** [florent37/Freezer#14]
I followed readme file, but i get this error

```
Error:(31, 35) error: cannot assign a value to final variable CREATOR
Error:(31, 46) error: incompatible types: List<Article> cannot be converted to Creator<Article>
Error:(73, 24) error: no suitable method found for insertForArticle(SQLiteDatabase,Creator<Article>,long,String)
method ArticleCursorHelper.insertForArticle(SQLiteDatabase,Article,long,String) is not applicable
(argument mismatch; Creator<Article> cannot be converted to Article)
method ArticleCursorHelper.insertForArticle(SQLiteDatabase,List<Article>,long,String) is not applicable
(argument mismatch; Creator<Article> cannot be converted to List<Article>)
Error:(88, 24) error: no suitable method found for updateForArticle(SQLiteDatabase,Creator<Article>,Long,String)
method ArticleCursorHelper.updateForArticle(SQLiteDatabase,Article,long,String) is not applicable
(argument mismatch; Creator<Article> cannot be converted to Article)
method ArticleCursorHelper.updateForArticle(SQLiteDatabase,List<Article>,long,String) is not applicable
(argument mismatch; Creator<Article> cannot be converted to List<Article>)
```

here Article class 

`@Model
public class Article implements Parcelable {

    String title;
    String imageUrl;
    Date date;
    String content;
    String description;
    String author;
    List<String> tags;
    String comments;
    String formattedDate;

    public String getTitle() {
        return title;
    }

    public Article setTitle(String title) {
        this.title = title;
        return this;
    }

    public Article setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
        return this;
    }

    public Date getDate() {
        return date;
    }

    public Article setDate(long date) {
        this.date = new Date(date);
        this.formattedDate = DateUtils.getRelativeTimeSpanString(date).toString();
        return this;
    }

    public String getContent() {
        return content;
    }

    public Article setContent(String content) {
        this.content = content;
        return this;
    }

    public String getAuthor() {
        return author;
    }

    public Article setAuthor(String author) {
        this.author = author;
        return this;
    }

    public String getDescription() {
        return description;
    }

    public Article setDescription(String description) {
        this.description = description;
        return this;
    }

    public List<String> getTags() {
        return tags;
    }

    public Article setTags(List<String> tags) {
        this.tags = tags;
        return this;
    }

    public String getComments() {
        return comments;
    }

    public Article setComments(String comments) {
        this.comments = comments;
        return this;
    }

    public String getFormattedDate() {
        return formattedDate;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.title);
        dest.writeString(this.imageUrl);
        dest.writeLong(date != null ? date.getTime() : -1);
        dest.writeString(this.content);
        dest.writeString(this.description);
        dest.writeString(this.author);
        dest.writeStringList(this.tags);
        dest.writeString(this.comments);
        dest.writeString(this.formattedDate);
    }

    public Article() {
    }

    protected Article(Parcel in) {
        this.title = in.readString();
        this.imageUrl = in.readString();
        long tmpDate = in.readLong();
        this.date = tmpDate == -1 ? null : new Date(tmpDate);
        this.content = in.readString();
        this.description = in.readString();
        this.author = in.readString();
        this.tags = in.createStringArrayList();
        this.comments = in.readString();
        this.formattedDate = in.readString();
    }

    public static final Parcelable.Creator<Article> CREATOR = new Parcelable.Creator<Article>() {
        public Article createFromParcel(Parcel source) {
            return new Article(source);
        }

        public Article[] newArray(int size) {
            return new Article[size];
        }
    };
}
`

and i cannot find Freezer class also after build

**Comment by florent37** [comment]
can you try with an `@Ignore` before the CREATOR ?
I'll try ingore it as default in a future version
