### ISSUE TITLE
does it support the query like sql "in" statement?

### ISSUE THREAD

**Issue by OVERSKY2003** [florent37/Freezer#19]
now I need to use a loop to get the records for multiple ids. Can I use something like "in" of sql to query once and get all the records

"select * from table where id in (10,20,30)"

**Comment by florent37** [comment]
Hello, nope It's not implémentés yet but I can do it for you ;)

**Comment by OVERSKY2003** [comment]
Thank you very much for your quick response. I also accounted the same issue #17 when access database in multithread . Now I use synchronized for all db manipulations(both for read and write) , so that only one thread to access db to prevent these issue. Any good suggestion for this?

**Comment by florent37** [comment]
done ;) check the 2.0.2
