### ISSUE TITLE
Cannot find UserEntityManager.

### ISSUE THREAD

**Issue by vipulyaara** [florent37/Freezer#22]
I know this sounds like a stupid question. I am fairly new to this architecture. I couldn't find `UserEntityManager` and `CatEntityManager` classes in the demo, that seems to be in 
`com.github.florent37.orm.model.CatEntityManager` and 
`com.github.florent37.orm.model.UserEntityManager`, but are not. How to resolve this?

**Comment by florent37** [comment]
just build the application once
