### ISSUE TITLE
List<Long> creates helper classes with Integer

### ISSUE THREAD

**Issue by zebroc** [florent37/Freezer#29]
Reproduce:

Create a POJO, like so:

@Model
public class Place {
    public String name;
    @Id
    public long id;
    public List<Long> numbers;
}

Then build the project --> Android Studio will give you an error:

incompatible types: List<Integer> cannot be converted to List<Long>

in PlaceCursorHelper

**Comment by florent37** [comment]
you did not give a type to your list ?

**Comment by zebroc** [comment]
I did. Github just does not show it ;)

List is of Type Long --> List(Long)

**Comment by florent37** [comment]
I fixed this on the 2.0.7 👍
