### ISSUE TITLE
Duplicates within relations

### ISSUE THREAD

**Issue by zebroc** [florent37/Freezer#30]
Duplicate entries of relations are created, when the parent entity is being updated.

Scenario: The app fetches data from an API & stores it in a table, this is the model:

Tour {
List(Place) places;
…
}

Step 1: App fetches data, like fetchAllTours()
Step 2: A tour is added on API side, i.e. all existing tours stay the same --> fetchAllTours()

All the existing tours get updated in the DB now, but each time a new row in the pivot table ("TOUR_PLACE") is being created. Resulting in duplicates: Getting one of the already existing Tours from the DB will now have each place twice.

**Comment by graphee-gabriel** [comment]
I have the same problem
Setting @Id on the ID field i get from Json, seems to override the ID from the server by an autogenerated ID.
It therefores creates duplicates.
