### ISSUE TITLE
SQLiteException: no such table after adding a new Model

### ISSUE THREAD

**Issue by zebroc** [florent37/Freezer#31]
I added a new Model class 'ATM' and when I start the app I get:

SQLiteException: no such table: ATM (code 1): , while compiling: INSERT OR REPLACE  INTO ATM(att1,att2,att3,att4,att5) VALUES (?,?,?,?,?)

Do I actually need to run a Migration to add a table?

(That's what I plan to do as a workaround)

**Comment by florent37** [comment]
If you modified your model, yes, you'll need a migration

2017-03-20 16:35 GMT+01:00 Marc Herbrechter <notifications@github.com>:

**Comment by zebroc** [comment]
I added a model. It wasn't there before.

Before there were the classes 'House', 'Hotel' and 'Car'. All with @Model annotations.

Then I added 'ATM', with @Model annotation.

Still need a migration?

**Comment by florent37** [comment]
If its a new model, you don't need migration usually

Le 20 mars 2017 17:29, "Marc Herbrechter" <notifications@github.com> a
écrit :

**Comment by zebroc** [comment]
Did not work for me.

When I delete the app's data & restart, it creates the DB with the new model included.

But if I install the old app version, populate the DB and then install the new app version (with the added model) it crashes with above mentioned error.

**Comment by fpoyer** [comment]
This is an old issue, but the given answers mislead us somewhat, so I'd like to clarify:
- what @florent37 says is that if your (whole) model is **brand** new, meaning it never was deployed on the device, then you don't need a migration
- but as @zebroc discovered, if you change your model *in any way*, including by adding a class totally unrelated to the previous model, then you definitely need a migration to handle devices where the previous model was deployed. Simplest migration (just create the empty table(s)) is:
```
for(String s : MyNewModelClassEntityManager.create()) database.execSQL(s);
```

**Comment by zebroc** [comment]
I have replaced Freezer with Room and since I assume the whole project is abandoned, I'll close the issue with the suggestion to do the same to others... :)
